spring:
  application:
    name: api-gateway

server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: investment-service
          uri: lb://investment-service
          predicates:
            - Path=/investments/**