
spring:
  application:
    name: user-service

  r2dbc: 
    url: ${PG_URL_USER}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    show-sql: true
    properties:
      logLevel: DEBUG

  # sql:
  #   initialization-mode: always
  #   schema-location: classpath:schema.sql

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc.connection: DEBUG
    br.com.bank.user_service: DEBUG

server: 
  port: 8181

eureka: 
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true
    io.r2dbc.postgresql.QUERY: DEBUG